# Generated by Django 4.2.30 on 2026-06-12 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('about', models.TextField(verbose_name='about')),
                ('position', models.CharField(max_length=100, verbose_name='position')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='player name')),
                ('about', models.TextField(verbose_name='about')),
                ('year', models.PositiveIntegerField(verbose_name='player year')),
                ('number', models.PositiveIntegerField(verbose_name='player number')),
                ('country', models.CharField(max_length=100, verbose_name='player country')),
                ('matches', models.PositiveIntegerField(verbose_name='matches')),
                ('count', models.PositiveIntegerField(verbose_name='counts')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Image')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='team.position', verbose_name='position')),
            ],
        ),
    ]
