# Generated by Django 4.2.30 on 2026-06-12 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Stadium name')),
                ('established_year', models.PositiveIntegerField(verbose_name='Year established')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('description', models.TextField(blank=True, verbose_name='About the stadium')),
            ],
        ),
        migrations.CreateModel(
            name='StadiumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='Image')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Image title')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main image')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.stadium', verbose_name='Stadium')),
            ],
        ),
    ]
