# Generated by Django 4.2.30 on 2026-06-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
