# Generated by Django 4.2.30 on 2026-06-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_stadium_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadiumimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Image'),
        ),
    ]
