# Generated by Django 4.2.30 on 2026-06-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_stadiumimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Yutuq nomi')),
                ('numb_achievement', models.PositiveIntegerField(verbose_name='Yutuqlar soni')),
            ],
        ),
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Date title')),
                ('content', models.TextField(verbose_name='Date content')),
                ('year', models.PositiveIntegerField(verbose_name='Sanasi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Legend name')),
                ('about', models.TextField(verbose_name='About of legend')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Legend image')),
            ],
        ),
    ]
